package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import com.google.android.gms.ads.internal.util.X;
import com.hs.rtovehicledetail.vahan.vehicleregistrationdetails.rtoapp.BuildConfig;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

public final class F {
    public static final C2331p<Long> A = C2331p.a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final C2331p<Long> Aa = C2331p.a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final C2331p<Boolean> Ab = C2331p.a(1, "gads:msa:experiments:ps:enabled", (Boolean) false);
    public static final C2331p<Boolean> Ac = C2331p.a(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", (Boolean) true);
    private static final C2331p<String> Ad = C2331p.a(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
    public static final C2331p<Integer> Ae = C2331p.a(1, "gads:offline_signaling:log_maximum", 100);
    public static final C2331p<Boolean> Af = C2331p.a(1, "gads:can_open_app_and_open_app_action:enabled", (Boolean) false);
    public static final C2331p<Boolean> B = C2331p.a(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final C2331p<Boolean> Ba = C2331p.a(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final C2331p<Integer> Bb = C2331p.a(1, "gads:gestures:a2:enabled", 0);
    public static final C2331p<Long> Bc = C2331p.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    private static final C2331p<Boolean> Bd = C2331p.a(1, "gads:nonagon:interstitial:enabled", (Boolean) true);
    public static final C2331p<Boolean> Be = C2331p.a(1, "gads:nativeads:template_signal:enabled", (Boolean) true);
    public static final C2331p<Boolean> Bf = C2331p.a(1, "gads:open_gmsg:set_uri_data_and_type:enabled", (Boolean) false);
    public static final C2331p<Boolean> C = C2331p.a(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final C2331p<Long> Ca = C2331p.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final C2331p<Boolean> Cb = C2331p.a(1, "gads:gestures:clearTd:enabled", (Boolean) false);
    public static final C2331p<Long> Cc = C2331p.a(1, "gads:parental_controls:timeout", 2000);
    private static final C2331p<String> Cd = C2331p.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    public static final C2331p<Boolean> Ce = C2331p.a(1, "gads:nativeads:media_content_aspect_ratio:enabled", (Boolean) true);
    public static final C2331p<Integer> Cf = C2331p.a(1, "gads:ad_error_api:min_version", 999999999);
    public static final C2331p<String> D = C2331p.a(1, "gads:video:codec_query_mime_types", BuildConfig.FLAVOR);
    public static final C2331p<Boolean> Da = C2331p.a(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final C2358pa<Boolean> Db = C0722Ga.f7042b;
    private static final C2331p<Integer> Dc = C2331p.a(1, "gads:cache:ad_request_timeout_millis", 250);
    private static final C2331p<Boolean> Dd = C2331p.a(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) true);
    public static final C2331p<Boolean> De = C2331p.a(1, "gads:nativeads:media_content_metadata:enabled", (Boolean) true);
    public static final C2331p<Boolean> Df = C2331p.a(1, "gads:forward_bow_error_string:enabled", (Boolean) false);
    public static final C2331p<Integer> E = C2331p.a(1, "gads:video:codec_query_minimum_version", 16);
    public static final C2331p<Boolean> Ea = C2331p.a(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    public static final C2331p<Boolean> Eb = C2331p.a(1, "gads:gestures:errorlogging:enabled", (Boolean) false);
    private static final C2331p<Integer> Ec = C2331p.a(1, "gads:cache:max_concurrent_downloads", 10);
    public static final C2331p<Boolean> Ed = C2331p.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) true);
    public static final C2331p<Boolean> Ee = C2331p.a(1, "gads:ar_ads:enabled", (Boolean) false);
    public static final C2331p<Boolean> Ef = C2331p.a(1, "gads:continue_on_process_response:enabled", (Boolean) false);
    public static final C2331p<Boolean> F = C2331p.a(1, "gads:video:set_black_background", (Boolean) false);
    public static final C2331p<Boolean> Fa = C2331p.a(1, "gads:use_system_ui_for_fullscreen:enabled", (Boolean) false);
    public static final C2331p<Long> Fb = C2331p.a(1, "gads:gestures:task_timeout", 2000);
    private static final C2331p<Boolean> Fc = C2331p.a(1, "gads:cache:downloader_use_high_priority", (Boolean) false);
    public static final C2331p<String> Fd = C2331p.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    public static final C2331p<Boolean> Fe = C2331p.a(1, "gads:precache_pool:verbose_logging", (Boolean) false);
    public static final C2331p<Boolean> Ff = C2331p.a(1, "gads:mediation_status_reporting:enabled", (Boolean) true);
    public static final C2331p<String> G = C2331p.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final C2331p<Boolean> Ga = C2331p.a(1, "gads:ad_overlay:collect_cutout_info:enabled", (Boolean) false);
    public static final C2331p<Boolean> Gb = C2331p.a(1, "gads:gestures:asig:enabled", (Boolean) false);
    private static final C2331p<Long> Gc = C2331p.a(1, "gads:cache:javascript_timeout_millis", 5000);
    private static final C2331p<Boolean> Gd = C2331p.a(1, "gads:nonagon:nativead:enabled", (Boolean) true);
    public static final C2331p<Integer> Ge = C2331p.a(1, "gads:rewarded_precache_pool:count", 0);
    public static final C2331p<Integer> Gf = C2331p.a(1, "gads:mediation_no_fill_error:min_version", 999999999);
    public static final C2331p<String> H = C2331p.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    private static final C2331p<Boolean> Ha = C2331p.a(1, "gads:impression_optimization_enabled", (Boolean) false);
    public static final C2331p<Boolean> Hb = C2331p.a(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final C2331p<Boolean> Hc = C2331p.a(1, "gads:cache:bind_on_foreground", (Boolean) false);
    private static final C2331p<String> Hd = C2331p.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final C2331p<Integer> He = C2331p.a(1, "gads:interstitial_precache_pool:count", 0);
    public static final C2331p<Integer> Hf = C2331p.a(1, "gads:offline_database_version:version", 1);
    public static final C2331p<String> I = C2331p.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    private static final C2331p<String> Ia = C2331p.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    public static final C2331p<Boolean> Ib = C2331p.a(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final C2331p<Boolean> Ic = C2331p.a(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final C2331p<Boolean> Id = C2331p.a(1, "gads:nonagon:banner:check_dp_size", (Boolean) true);
    public static final C2331p<String> Ie = C2331p.a(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
    public static final C2331p<Boolean> If = C2331p.a(1, "gads:offline_ads_notification:enabled", (Boolean) true);
    public static final C2331p<String> J = C2331p.a(1, "gad:mraid:version", "3.0");
    private static final C2331p<Integer> Ja = C2331p.a(1, "gads:banner_ad_pool:max_queues", 3);
    private static final C2331p<Boolean> Jb = C2331p.a(1, "gads:gestures:brt:enabled", (Boolean) true);
    public static final C2331p<Boolean> Jc = C2331p.a(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final C2331p<Boolean> Jd = C2331p.a(1, "gads:nonagon:rewarded:load_multiple_ads", (Boolean) true);
    public static final C2331p<String> Je = C2331p.a(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
    public static final C2331p<Boolean> Jf = C2331p.a(1, "gads:handle_click_recorded_event:enabled", (Boolean) false);
    public static final C2331p<Boolean> K = C2331p.a(1, "gads:mraid:expanded_interstitial_fix", (Boolean) false);
    private static final C2331p<Integer> Ka = C2331p.a(1, "gads:banner_ad_pool:max_pools", 3);
    public static final C2331p<Boolean> Kb = C2331p.a(1, "gads:gestures:fpi:enabled", (Boolean) false);
    public static final C2331p<Long> Kc = C2331p.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    private static final C2331p<Boolean> Kd = C2331p.a(1, "gads:nonagon:return_last_error_code", (Boolean) false);
    public static final C2331p<String> Ke = C2331p.a(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
    public static final C2331p<Boolean> Kf = C2331p.a(1, "gads:default_network_type_fine_to_unknown:enabled", (Boolean) true);
    public static final C2331p<Boolean> L = C2331p.a(1, "gads:mraid:initial_size_fallback", (Boolean) false);
    public static final C2331p<Boolean> La = C2331p.a(1, "gads:delay_banner_renderer:enabled", (Boolean) true);
    public static final C2331p<Boolean> Lb = C2331p.a(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final C2331p<Boolean> Lc = C2331p.a(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final C2331p<Boolean> Ld = C2331p.a(1, "gads:nonagon:return_no_fill_error_code", (Boolean) false);
    public static final C2331p<String> Le = C2331p.a(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
    public static final C2331p<Integer> M = C2331p.a(1, "gads:content_vertical_fingerprint_number", 100);
    private static final C2331p<Boolean> Ma = C2331p.a(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final C2331p<Boolean> Mb = C2331p.a(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final C2331p<Boolean> Mc = C2331p.a(1, "gads:cache:connection_per_read", (Boolean) false);
    public static final C2331p<Boolean> Md = C2331p.a(1, "gads:nonagon:continue_on_no_fill", (Boolean) false);
    public static final C2331p<Integer> Me = C2331p.a(1, "gads:rewarded_precache_pool:size", 1);
    public static final C2331p<Integer> N = C2331p.a(1, "gads:content_vertical_fingerprint_bits", 23);
    private static final C2331p<Boolean> Na = C2331p.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final C2331p<String> Nb = C2331p.a(1, "gads:gestures:pk", BuildConfig.FLAVOR);
    public static final C2331p<Long> Nc = C2331p.a(1, "gads:cache:connection_timeout", 5000);
    private static final C2331p<Boolean> Nd = C2331p.a(1, "gads:nonagon:open_not_loaded_interstitial", (Boolean) true);
    public static final C2331p<Integer> Ne = C2331p.a(1, "gads:interstitial_precache_pool:size", 1);
    public static final C2331p<Integer> O = C2331p.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    private static final C2331p<String> Oa = C2331p.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final C2331p<Boolean> Ob = C2331p.a(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final C2331p<Long> Oc = C2331p.a(1, "gads:cache:read_only_connection_timeout", 5000);
    public static final C2331p<Boolean> Od = C2331p.a(1, "gads:nonagon:separate_timeout:enabled", (Boolean) true);
    public static final C2331p<Integer> Oe = C2331p.a(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
    public static final C2331p<String> P = C2331p.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    private static final C2331p<String> Pa = C2331p.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final C2331p<Boolean> Pb = C2331p.a(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final C2331p<Boolean> Pc = C2331p.a(1, "gads:cache:read_inner_data_source_if_gcache_miss", (Boolean) false);
    public static final C2331p<Integer> Pd = C2331p.a(1, "gads:nonagon:request_timeout:seconds", 60);
    public static final C2331p<Integer> Pe = C2331p.a(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
    public static final C2331p<String> Q = C2331p.a(1, "gads:content_fetch_exclude_view_tag", "none");
    private static final C2331p<Integer> Qa = C2331p.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final C2331p<Boolean> Qb = C2331p.a(1, "gads:gestures:init_new_thread:enabled", (Boolean) true);
    public static final C2331p<Boolean> Qc = C2331p.a(1, "gads:cache:read_inner_data_source_if_gcache_not_downloaded", (Boolean) false);
    public static final C2331p<Boolean> Qd = C2331p.a(1, "gads:nonagon:banner_recursive_renderer", (Boolean) false);
    public static final C2331p<String> Qe = C2331p.a(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final C2331p<Boolean> R = C2331p.a(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    private static final C2331p<Integer> Ra = C2331p.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final C2331p<Boolean> Rb = C2331p.a(1, "gads:gestures:pds:enabled", (Boolean) true);
    public static final C2331p<Boolean> Rc = C2331p.a(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final C2331p<Boolean> Rd = C2331p.a(1, "gads:nonagon:app_stats_lock:enabled", (Boolean) false);
    public static final C2331p<String> Re = C2331p.a(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final C2331p<Boolean> S = C2331p.a(1, "gads:content_fetch_enable_new_content_score", (Boolean) false);
    private static final C2331p<Integer> Sa = C2331p.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    private static final C2331p<Integer> Sb = C2331p.a(1, "gads:gestures:as2percentage", 0);
    public static final C2331p<String> Sc = C2331p.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final C2331p<Boolean> Sd = C2331p.a(1, "gads:nonagon:app_stats_main_thread:enabled", (Boolean) false);
    public static final C2331p<String> Se = C2331p.a(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final C2331p<Boolean> T = C2331p.a(1, "gads:content_fetch_enable_serve_once", (Boolean) false);
    private static final C2331p<String> Ta = C2331p.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final C2331p<Boolean> Tb = C2331p.a(1, "gads:gestures:ns:enabled", (Boolean) true);
    public static final C2331p<Integer> Tc = C2331p.a(1, "gads:http_assets_cache:time_out", 100);
    public static final C2331p<Boolean> Td = C2331p.a(1, "gads:uri_query_to_map_bg_thread:enabled", (Boolean) false);
    public static final C2331p<String> Te = C2331p.a(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
    public static final C2331p<Boolean> U = C2331p.a(1, "gads:sai:enabled", (Boolean) true);
    private static final C2331p<Integer> Ua = C2331p.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final C2331p<Boolean> Ub = C2331p.a(1, "gads:gestures:vdd:enabled", (Boolean) false);
    public static final C2331p<Boolean> Uc = C2331p.a(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final C2331p<Boolean> Ud = C2331p.a(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", (Boolean) true);
    public static final C2331p<Integer> Ue = C2331p.a(1, "gads:app_open_precache_pool:count", 0);
    public static final C2331p<String> V = C2331p.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    private static final C2331p<Integer> Va = C2331p.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final C2331p<Boolean> Vb = C2331p.a(1, "gads:native:asset_view_touch_events", (Boolean) false);
    public static final C2331p<Boolean> Vc = C2331p.a(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final C2331p<Boolean> Vd = C2331p.a(1, "gads:active_view_gmsg_separate_pool:enabled", (Boolean) true);
    public static final C2331p<String> Ve = C2331p.a(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
    public static final C2331p<String> W = C2331p.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
    private static final C2331p<Long> Wa = C2331p.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final C2331p<Boolean> Wb = C2331p.a(1, "gads:native:set_touch_listener_on_asset_views", (Boolean) true);
    public static final C2331p<Boolean> Wc = C2331p.a(1, "gads:chrome_custom_tabs_browser_v2:enabled", (Boolean) false);
    private static final C2331p<Boolean> Wd = C2331p.a(1, "gads:nonagon:service:enabled", (Boolean) true);
    public static final C2331p<Integer> We = C2331p.a(1, "gads:app_open_precache_pool:size", 1);
    public static final C2331p<Boolean> X = C2331p.a(1, "gads:sai:using_macro:enabled", (Boolean) false);
    private static final C2331p<Long> Xa = C2331p.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final C2331p<Boolean> Xb = C2331p.a(1, "gads:ais:enabled", (Boolean) true);
    public static final C2331p<Boolean> Xc = C2331p.a(1, "gads:chrome_custom_tabs_for_native_ads:enabled", (Boolean) false);
    public static final C2331p<Boolean> Xd = C2331p.a(1, "gads:nonagon:dpl_cancel_destroy_webview:enabled", (Boolean) false);
    public static final C2331p<Integer> Xe = C2331p.a(1, "gads:app_open_precache_pool:ad_time_limit", 14400);
    public static final C2331p<String> Y = C2331p.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    private static final C2331p<Float> Ya = C2331p.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final C2331p<Boolean> Yb = C2331p.a(1, "gads:stav:enabled", (Boolean) false);
    public static final C2331p<Long> Yc = C2331p.a(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final C2331p<Boolean> Yd = C2331p.a(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    public static final C2331p<Boolean> Ye = C2331p.a(1, "gads:memory_leak:b129558083", (Boolean) false);
    public static final C2331p<Long> Z = C2331p.a(1, "gads:sai:timeout_ms", -1);
    private static final C2331p<Float> Za = C2331p.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final C2331p<Boolean> Zb = C2331p.a(1, "gads:send_available_disk_space:enabled", (Boolean) false);
    public static final C2331p<String> Zc = C2331p.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final C2331p<Boolean> Zd = C2331p.a(1, "gads:signals:app_index:enabled", (Boolean) false);
    public static final C2331p<Boolean> Ze = C2331p.a(1, "gads:unhandled_event_reporting:enabled", (Boolean) false);
    public static final C2331p<String> _a = C2331p.a(1, "gads:spherical_video:vertex_shader", BuildConfig.FLAVOR);
    private static final C2331p<String> _b;
    public static final C2331p<String> _c = C2331p.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final C2331p<Boolean> _d = C2331p.a(1, "gads:signals:attestation_token:enabled", (Boolean) false);
    public static final C2331p<Boolean> _e = C2331p.a(1, "gads:response_info:enabled", (Boolean) true);

    /* renamed from: a  reason: collision with root package name */
    public static final C2331p<String> f6786a = C2331p.a(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final C2331p<Integer> aa = C2331p.a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final C2331p<String> ab = C2331p.a(1, "gads:spherical_video:fragment_shader", BuildConfig.FLAVOR);
    public static final C2331p<String> ac = C2331p.a(1, "gads:sdk_core_constants:caps", BuildConfig.FLAVOR);
    public static final C2331p<String> ad = C2331p.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final C2331p<Boolean> ae = C2331p.a(1, "gads:signals:cache:enabled", (Boolean) false);
    public static final C2331p<Boolean> af = C2331p.a(1, "gads:csi:interstitial_failed_to_show:enabled", (Boolean) false);

    /* renamed from: b  reason: collision with root package name */
    private static final C2331p<String> f6787b = C2331p.a(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final C2331p<Boolean> ba = C2331p.a(1, "gads:sai:app_measurement_enabled3", (Boolean) false);
    public static final C2331p<Boolean> bb = C2331p.a(1, "gads:include_local_global_rectangles", (Boolean) false);
    private static final C2331p<Boolean> bc = C2331p.a(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final C2331p<String> bd = C2331p.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    private static final C2331p<Boolean> be = C2331p.a(1, "gads:signals:doritos:enabled", (Boolean) false);
    public static final C2331p<Boolean> bf = C2331p.a(1, "gads:csi:mediation_failure:enabled", (Boolean) false);

    /* renamed from: c  reason: collision with root package name */
    private static final C2358pa<Boolean> f6788c = C0696Fa.f6866d;
    public static final C2331p<Integer> ca = C2331p.a(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
    public static final C2331p<Long> cb = C2331p.a(1, "gads:position_watcher:throttle_ms", 200);
    public static final C2331p<String> cc = C2331p.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final C2331p<Integer> cd = C2331p.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final C2331p<Boolean> ce = C2331p.a(1, "gads:signals:doritos:v1:enabled", (Boolean) false);
    public static final C2331p<String> cf = C2331p.a(1, "gads:csi:error_parsing:regex", "^(\\d+)");

    /* renamed from: d  reason: collision with root package name */
    private static final C2331p<Integer> f6789d = C2331p.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final C2331p<Boolean> da = C2331p.a(1, "gads:sai:force_through_reflection", (Boolean) true);
    public static final C2331p<Long> db = C2331p.a(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    private static final C2331p<String> dc = C2331p.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final C2331p<Integer> dd = C2331p.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    private static final C2331p<Boolean> de = C2331p.a(1, "gads:signals:doritos:v2:immediate:enabled", (Boolean) false);
    public static final C2331p<Boolean> df = C2331p.a(1, "gads:signal_collection_without_rendering:enabled", (Boolean) true);

    /* renamed from: e  reason: collision with root package name */
    public static final C2331p<String> f6790e = C2331p.a(1, "gads:video_exo_player:version", "3");
    public static final C2331p<Boolean> ea = C2331p.a(1, "gads:sai:gmscore_availability_check_disabled", (Boolean) false);
    public static final C2331p<Boolean> eb = C2331p.a(1, "gads:position_watcher:enable_scroll_aware_ads", (Boolean) false);
    public static final C2331p<String> ec = C2331p.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final C2331p<Boolean> ed = C2331p.a(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final C2331p<Boolean> ee = C2331p.a(1, "gads:signals:location:enabled", (Boolean) false);
    public static final C2331p<Integer> ef = C2331p.a(1, "gads:native_ads_signal:timeout", 1000);

    /* renamed from: f  reason: collision with root package name */
    public static final C2331p<Integer> f6791f = C2331p.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final C2331p<Boolean> fa = C2331p.a(1, "gads:sai:logging_disabled_for_drx", (Boolean) false);
    public static final C2331p<Boolean> fb = C2331p.a(1, "gads:position_watcher:send_scroll_data", (Boolean) false);
    public static final C2331p<Boolean> fc = C2331p.a(1, "gads:native:get_native_ad_view_signals", (Boolean) false);
    public static final C2331p<Boolean> fd = C2331p.a(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    private static final C2331p<Boolean> fe = C2331p.a(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    public static final C2331p<Integer> ff = C2331p.a(1, "gads:signal_v2:min_version", 19677000);

    /* renamed from: g  reason: collision with root package name */
    public static final C2331p<Integer> f6792g = C2331p.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final C2331p<Boolean> ga = C2331p.a(1, "gads:sai:app_measurement_npa_enabled", (Boolean) false);
    private static final C2331p<Boolean> gb = C2331p.a(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final C2331p<Integer> gc = C2331p.a(1, "gads:native_video_load_timeout", 10);
    public static final C2331p<Boolean> gd = C2331p.a(1, "gad:interstitial_multi_window_method", (Boolean) false);
    public static final C2331p<Boolean> ge = C2331p.a(1, "gads:signals:parental_control:enabled", (Boolean) false);
    public static final C2331p<Boolean> gf = C2331p.a(2, "DISABLE_CRASH_REPORTING", (Boolean) false);

    /* renamed from: h  reason: collision with root package name */
    public static final C2331p<Integer> f6793h = C2331p.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final C2331p<Boolean> ha = C2331p.a(1, "gads:idless:idless_disables_attestation", (Boolean) false);
    public static final C2331p<Boolean> hb = C2331p.a(1, "gads:extra_sdk_versions_for_crash_reports:enabled", (Boolean) false);
    private static final C2331p<Integer> hc = C2331p.a(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final C2331p<Integer> hd = C2331p.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final C2331p<Boolean> he = C2331p.a(1, "gads:signals:video_decoder:enabled", (Boolean) false);
    public static final C2331p<Boolean> hf = C2331p.a(1, "gads:paid_event_listener:enabled", (Boolean) false);
    public static final C2331p<Integer> i = C2331p.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final C2331p<Boolean> ia = C2331p.a(1, "gads:interstitial:app_must_be_foreground:enabled", (Boolean) false);
    public static final C2331p<String> ib = C2331p.a(1, "gads:logged_adapter_version_classes", BuildConfig.FLAVOR);
    public static final C2331p<Boolean> ic = C2331p.a(1, "gads:omid:native_video_ad_user_action_event:enabled", (Boolean) false);
    public static final C2331p<Boolean> id = C2331p.a(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final C2331p<Boolean> ie = C2331p.a(1, "gads:signals:app_version_name:enabled", (Boolean) false);

    /* renamed from: if  reason: not valid java name */
    public static final C2331p<Boolean> f0if = C2331p.a(1, "gads:interscroller_ad:enabled", (Boolean) true);
    public static final C2331p<Integer> j = C2331p.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final C2331p<Boolean> ja = C2331p.a(1, "gads:interstitial:foreground_report:enabled", (Boolean) false);
    public static final C2331p<Long> jb = C2331p.a(1, "gads:rtb_v1_1:signal_timeout_ms", 1000);
    public static final C2331p<Boolean> jc = C2331p.a(1, "gads:enable_native_media_aspect_ratio", (Boolean) true);
    public static final C2331p<Boolean> jd = C2331p.a(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    public static final C2331p<Boolean> je = C2331p.a(1, "gads:signals:banner_hardware_acceleration:enabled", (Boolean) false);
    public static final C2331p<Boolean> jf = C2331p.a(1, "gads:interscroller_ad:refresh:enabled", (Boolean) false);
    public static final C2331p<Integer> k = C2331p.a(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    public static final C2331p<Boolean> ka = C2331p.a(1, "gads:webview:error_web_response:enabled", (Boolean) false);
    public static final C2331p<Boolean> kb = C2331p.a(1, "gads:rtb_signal:enabled", (Boolean) true);
    public static final C2331p<Boolean> kc = C2331p.a(1, "gads:native:media_content_main_image:enabled", (Boolean) true);
    public static final C2331p<Boolean> kd = C2331p.a(1, "gad:publisher_testing:force_local_request:enabled", (Boolean) true);
    public static final C2331p<Boolean> ke = C2331p.a(1, "gads:signals:native_hardware_acceleration:enabled", (Boolean) false);
    public static final C2331p<Boolean> kf = C2331p.a(1, "gads:is_in_scroll_view_new_api:enabled", (Boolean) true);
    public static final C2331p<String> l = C2331p.a(1, "gads:video_exo_player:precache_exceptions", BuildConfig.FLAVOR);
    public static final C2331p<Boolean> la = C2331p.a(1, "gads:webview:pause_interstitial:enabled", (Boolean) true);
    public static final C2331p<Boolean> lb = C2331p.a(1, "gads:rtb_v1_1:cld:enabled", (Boolean) true);
    public static final C2331p<String> lc = C2331p.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final C2331p<String> ld = C2331p.a(1, "gad:publisher_testing:force_local_request:enabled_list", BuildConfig.FLAVOR);
    private static final C2331p<Boolean> le = C2331p.a(1, "gads:attestation_token:enabled", (Boolean) false);
    public static final C2331p<Boolean> lf = C2331p.a(1, "gads:policy_validator_for_all_pubs:enabled", (Boolean) false);
    public static final C2331p<Integer> m = C2331p.a(1, "gads:video_exo_player:min_retry_count", -1);
    private static final C2331p<Boolean> ma = C2331p.a(1, "gads:rsku:webviewgone:kill_process:enabled", (Boolean) false);
    public static final C2331p<Boolean> mb = C2331p.a(1, "gads:rtb_v1_1:cld:check_regex:enabled", (Boolean) true);
    private static final C2331p<Boolean> mc = C2331p.a(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final C2331p<String> md = C2331p.a(1, "gad:publisher_testing:force_local_request:disabled_list", BuildConfig.FLAVOR);
    public static final C2331p<Long> me = C2331p.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final C2331p<String> mf = C2331p.a(1, "gad:publisher_testing:policy_validator:enabled_list", BuildConfig.FLAVOR);
    public static final C2331p<Boolean> n = C2331p.a(1, "gads:video_exo_player:fmp4_extractor_enabled", (Boolean) false);
    public static final C2331p<Boolean> na = C2331p.a(1, "gads:webviewgone:kill_process:enabled", (Boolean) false);
    public static final C2331p<String> nb = C2331p.a(1, "gads:rtb_logging:regex", "(?!)");
    public static final C2331p<Boolean> nc = C2331p.a(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final C2331p<Integer> nd = C2331p.a(1, "gad:http_redirect_max_count:times", 8);
    public static final C2331p<Integer> ne = C2331p.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final C2331p<Integer> nf = C2331p.a(1, "gads:policy_validator_layoutparam:flags", 808);
    public static final C2331p<Integer> o = C2331p.a(1, "gads:video_stream_cache:limit_count", 5);
    private static final C2331p<Boolean> oa = C2331p.a(1, "gads:rsku:webviewgone:new_onshow:enabled", (Boolean) true);
    public static final C2331p<Boolean> ob = C2331p.a(1, "gads:presentation_error:urls_enabled", (Boolean) false);
    public static final C2331p<Boolean> oc = C2331p.a(1, "gads:native:media_view_match_parent:enabled", (Boolean) false);
    public static final C2331p<Boolean> od = C2331p.a(1, "gads:omid:enabled", (Boolean) true);
    public static final C2331p<Integer> oe = C2331p.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
    public static final C2331p<Boolean> of = C2331p.a(2, "NATIVE_AD_DEBUGGER_ENABLED", (Boolean) true);
    public static final C2331p<Integer> p = C2331p.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final C2331p<Boolean> pa = C2331p.a(1, "gads:webviewgone:new_onshow:enabled", (Boolean) false);
    public static final C2331p<Boolean> pb = C2331p.a(1, "gads:rtb_interstitial:use_fullscreen_monitor", (Boolean) false);
    public static final C2331p<Boolean> pc = C2331p.a(1, "gads:native:count_impression_for_assets", (Boolean) false);
    public static final C2331p<Integer> pd = C2331p.a(1, "gads:omid:destroy_webview_delay", 1000);
    public static final C2331p<Integer> pe = C2331p.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
    public static final C2331p<Integer> pf = C2331p.a(1, "gads:policy_validator_overlay_width:dp", 350);
    public static final C2331p<Integer> q = C2331p.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final C2331p<Boolean> qa = C2331p.a(1, "gads:webview:pause_resume:enabled", (Boolean) true);
    public static final C2331p<Boolean> qb = C2331p.a(1, "gads:native_required_assets:enabled", (Boolean) false);
    private static final C2331p<Boolean> qc = C2331p.a(1, "gads:instream_ad:enabled", (Boolean) true);
    private static final C2331p<Boolean> qd = C2331p.a(1, "gads:omid_1_3_activate:enabled", (Boolean) false);
    public static final C2331p<Integer> qe = C2331p.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
    public static final C2331p<Integer> qf = C2331p.a(1, "gads:policy_validator_overlay_height:dp", 140);
    public static final C2331p<Long> r = C2331p.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final C2331p<String> ra = C2331p.a(1, "gads:webview_cookie_url", "googleads.g.doubleclick.net");
    public static final C2331p<Boolean> rb = C2331p.a(1, "gads:v1_1:adapter_initialization:enabled", (Boolean) true);
    public static final C2331p<Boolean> rc = C2331p.a(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final C2331p<Boolean> rd = C2331p.a(1, "gads:omid_1_3_create_html_session:enabled", (Boolean) false);
    private static final C2358pa<Boolean> re = C0748Ha.f7158a;
    public static final C2331p<Boolean> rf = C2331p.a(1, "gads:use_wide_viewport:enabled", (Boolean) false);
    public static final C2331p<Long> s = C2331p.a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    private static final C2331p<Boolean> sa = C2331p.a(1, "gads:new_rewarded_ad:enabled", (Boolean) true);
    public static final C2331p<Integer> sb = C2331p.a(1, "gads:adapter_initialization:min_sdk_version", 15301000);
    private static final C2331p<Boolean> sc = C2331p.a(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    public static final C2331p<Boolean> sd = C2331p.a(1, "gads:omid_1_3_create_js_session:enabled", (Boolean) false);

    /* renamed from: se  reason: collision with root package name */
    public static final C2331p<Boolean> f6794se = C2331p.a(1, "gads:consent:shared_preference_reading:enabled", (Boolean) true);
    public static final C2331p<Boolean> sf = C2331p.a(1, "gads:load_with_overview_mode:enabled", (Boolean) false);
    public static final C2331p<Integer> t = C2331p.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final C2331p<Boolean> ta = C2331p.a(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final C2331p<Long> tb = C2331p.a(1, "gads:adapter_initialization:timeout", 30);
    private static final C2331p<String> tc = C2331p.a(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static final C2331p<Boolean> td = C2331p.a(1, "gads:omid_1_3_friendly_obstruction:enabled", (Boolean) false);
    public static final C2331p<Boolean> te = C2331p.a(1, "gads:consent:iab_consent_info:enabled", (Boolean) true);
    public static final C2331p<Boolean> tf = C2331p.a(1, "gads:wire_banner_listener_after_request:enabled", (Boolean) false);
    public static final C2331p<String> u = C2331p.a(1, "gads:video:metric_frame_hash_times", BuildConfig.FLAVOR);
    private static final C2331p<Long> ua = C2331p.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final C2331p<Long> ub = C2331p.a(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final C2331p<Long> uc = C2331p.a(1, "gads:auto_location_timeout", 2000);
    public static final C2331p<Boolean> ud = C2331p.a(1, "gads:omid_1_3_fire_loaded_event:enabled", (Boolean) false);
    public static final C2331p<Boolean> ue = C2331p.a(1, "gads:fc_consent:shared_preference_reading:enabled", (Boolean) true);
    public static final C2331p<Boolean> uf = C2331p.a(1, "gads:wire_rewarded_listener_after_request:enabled", (Boolean) false);
    public static final C2331p<Long> v = C2331p.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final C2331p<Boolean> va = C2331p.a(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final C2331p<Boolean> vb = C2331p.a(1, "gads:additional_video_csi:enabled", (Boolean) false);
    private static final C2331p<String> vc = C2331p.a(1, "gads:auto_location_timeout:experiment_id");
    private static final C2331p<Boolean> vd = C2331p.a(1, "gads:nonagon:banner:enabled", (Boolean) true);
    public static final C2331p<String> ve = C2331p.a(1, "gads:sp:json_string", BuildConfig.FLAVOR);
    public static final C2331p<Boolean> vf = C2331p.a(1, "gads:wire_app_open_listener_after_request:enabled", (Boolean) false);
    public static final C2331p<Boolean> w = C2331p.a(1, "gads:video:force_watermark", (Boolean) false);
    public static final C2331p<Boolean> wa = C2331p.a(1, "gads:rewarded:ssv_custom_data_enabled", (Boolean) true);
    public static final C2331p<Boolean> wb = C2331p.a(1, "gads:csi:enabled_per_sampling", (Boolean) false);
    private static final C2331p<Long> wc = C2331p.a(1, "gads:auto_location_interval", -1);
    private static final C2331p<String> wd = C2331p.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    public static final C2331p<Boolean> we = C2331p.a(1, "gads:nativeads:image:sample:enabled", (Boolean) true);
    public static final C2331p<Boolean> wf = C2331p.a(1, "gads:wire_interstitial_listener_after_request:enabled", (Boolean) false);
    public static final C2331p<Long> x = C2331p.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final C2331p<Long> xa = C2331p.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final C2331p<Boolean> xb = C2331p.a(1, "gads:initialization_csi:enabled", (Boolean) false);
    private static final C2331p<String> xc = C2331p.a(1, "gads:auto_location_interval:experiment_id");
    private static final C2331p<Boolean> xd = C2331p.a(1, "gads:nonagon:app_open:enabled", (Boolean) true);
    public static final C2331p<Integer> xe = C2331p.a(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final C2331p<Boolean> xf = C2331p.a(1, "gads:wire_ad_loader_listener_after_request:enabled", (Boolean) false);
    public static final C2331p<Boolean> y = C2331p.a(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final C2331p<Long> ya = C2331p.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    private static final C2331p<Boolean> yb = C2331p.a(1, "gads:initialization_csi_control:enabled", (Boolean) false);
    public static final C2331p<Boolean> yc = C2331p.a(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", (Boolean) true);
    public static final C2331p<Integer> yd = C2331p.a(1, "gads:app_open_beta:min_version", 999999999);
    public static final C2331p<Boolean> ye = C2331p.a(1, "gads:nativeads:pub_image_scale_type:enabled", (Boolean) true);
    public static final C2331p<Boolean> yf = C2331p.a(1, "gads:server_transaction_source:enabled", (Boolean) false);
    public static final C2331p<Integer> z = C2331p.a(1, "gads:video:spinner:scale", 4);
    public static final C2331p<Boolean> za = C2331p.a(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final C2331p<Boolean> zb = C2331p.a(1, "gads:msa:experiments:enabled", (Boolean) false);
    public static final C2331p<Boolean> zc = C2331p.a(1, "gads:get_request_signals_cld:enabled", (Boolean) false);
    public static final C2331p<Integer> zd = C2331p.a(1, "gads:app_open_ad_open_beta_api:min_version", 202490999);
    public static final C2331p<Boolean> ze = C2331p.a(1, "gads:offline_signaling:enabled", (Boolean) false);
    public static final C2331p<String> zf = C2331p.a(1, "gads:server_transaction_source:list", "Network");

    static {
        C2331p<String> a2 = C2331p.a(1, "gads:sdk_core_constants:experiment_id", (String) null);
        Qqa.d().b(a2);
        _b = a2;
    }

    public static List<String> a() {
        return Qqa.d().a();
    }

    public static void a(Context context) {
        X.a(new E(context));
    }

    /* JADX WARNING: type inference failed for: r0v1, types: [com.google.android.gms.internal.ads.y, com.google.android.gms.internal.ads.Ua] */
    public static void a(Context context, int i2, JSONObject jSONObject) {
        Qqa.c();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        C2712ua.a(new C2969y(Qqa.d(), edit, jSONObject));
        Qqa.d().a(edit, 1, jSONObject);
        Qqa.c();
        edit.commit();
    }

    public static List<String> b() {
        return Qqa.d().b();
    }
}
